Simplified "show" script

diff --git a/.custom/scripts/show b/.custom/scripts/show
--- a/.custom/scripts/show
+++ b/.custom/scripts/show
@@ -1,8 +1,4 @@
 #!/bin/bash
 
 # Shows the code of any of my scripts, like where for functions
-if [ $# -eq 0 ]; then
-	exit 1
-else
-	cat "${SCRIPTS}/$1"
-fi
+cat "${SCRIPTS}/$1" 2> /dev/null || echo "Error: not a script"
